# Must be unique in a given SonarQube instance
sonar.projectKey=br.edu.fatec:python-fire-google

sonar.projectName=python-fire-google
sonar.projectVersion=1.1
 
# Path is relative to the sonar-project.properties file.
# Replace "\" by "/" on Windows.
# This property is optional if sonar.modules is set. 
sonar.sources=.
 
# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

sonar.token=sqa_5740e8e453aa07dc4b72334e4511c700518b00ce
sonar.host.url=http://localhost:9000